# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjoint_PG',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adjoint_pédagogie',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adjoint_scolarité',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adjoint_secrétariat',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chef_Departement',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_du_temp_etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='Emploi_du_temp_etudiant/')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_du_temp_examin_etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('semestre', models.CharField(choices=[('semestre1', 'semestre1'), ('semestre2', 'semestre2')], default='semestre1', max_length=9)),
                ('image', models.ImageField(upload_to='Emploi_du_temp_examin_etudiant/')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
            options={
                'ordering': ('grade',),
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Matière',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Mat', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('Nom_Mat',),
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('semestre1', 'semestre1'), ('semestre2', 'semestre2')], default='semestre1', max_length=9)),
                ('note_CC', models.FloatField(default=0.0)),
                ('note_examin', models.FloatField(default=0.0)),
                ('note_ratrappage', models.FloatField(default=0.0)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Etudiant')),
                ('matière', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Matière')),
            ],
            options={
                'ordering': ('note_CC',),
            },
        ),
        migrations.CreateModel(
            name='parcour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('Doctorant', 'Doctorant')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pv_cpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pv_cpc/')),
                ('semestre', models.CharField(choices=[('semestre1', 'semestre1'), ('semestre2', 'semestre2')], default='semestre1', max_length=9)),
                ('description', models.CharField(default='', max_length=25)),
                ('parcour', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('Doctorant', 'Doctorant')], default='semestre1', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Filière',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Matière',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_du_temp_enseignant',
            fields=[
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Enseignant')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='Emploi_du_temp_enseignant/')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_du_temp_examin_enseignant',
            fields=[
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Enseignant')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='Emploi_du_temp_examin_enseignant/')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_CPC',
            fields=[
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Enseignant')),
                ('parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parcour')),
            ],
        ),
        migrations.AddField(
            model_name='responsable_matière',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Enseignant'),
        ),
        migrations.AddField(
            model_name='responsable_matière',
            name='matière',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Matière'),
        ),
        migrations.AddField(
            model_name='matière',
            name='Parcour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parcour'),
        ),
        migrations.AddField(
            model_name='matière',
            name='enseignat',
            field=models.ManyToManyField(to='accounts.Enseignant'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parcour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parcour'),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_examin_etudiant',
            name='parcour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parcour'),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_etudiant',
            name='parcour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parcour'),
        ),
        migrations.AddField(
            model_name='pv_cpc',
            name='responsable_cpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.Responsable_CPC'),
        ),
    ]
