# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180527_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv_cpc',
            name='file',
            field=models.FileField(upload_to='pv_cpc/'),
        ),
    ]
