# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emploi_du_temp_etudiant_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('Assistant', 'Assistant'), ('Maitre assistant B', 'Maitre assistant B'), ('Maitre assistant A', 'Maitre assistant A'), ('Maitre conference B', 'Maitre conference B'), ('Maitre conference A', 'Maitre conference A'), ('Professeur', 'Professeur')], default='Assistant', max_length=25),
        ),
    ]
