# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180530_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_filiere',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
