# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_document_filiere_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_pedagogie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='document_pedagogie/')),
                ('adjoint_pedagogie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Adjoint_pédagogie')),
            ],
        ),
        migrations.CreateModel(
            name='document_secretariat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='document_secretariat/')),
                ('adjoint_secretariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Adjoint_secrétariat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
