# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_document_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.Etudiant'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='matière',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes', to='accounts.Matière'),
        ),
    ]
