# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180531_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichier_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='document_secretariat/')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Enseignant')),
                ('matièere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Matière')),
            ],
        ),
    ]
