# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fichier_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier_note',
            old_name='matièere',
            new_name='matière',
        ),
    ]
