# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180605_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receiver',
            new_name='commun',
        ),
    ]
