# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180605_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senders',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='commun',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.senders'),
        ),
    ]
