# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180605_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commun',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='commun',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='senders',
            name='user',
        ),
        migrations.DeleteModel(
            name='commun',
        ),
        migrations.DeleteModel(
            name='senders',
        ),
    ]
