# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180605_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploi_du_temp_enseignant',
            old_name='Dimanche',
            new_name='Dimanche_S1',
        ),
        migrations.RenameField(
            model_name='emploi_du_temp_enseignant',
            old_name='Jeudi',
            new_name='Dimanche_S2',
        ),
        migrations.RenameField(
            model_name='emploi_du_temp_enseignant',
            old_name='Lundi',
            new_name='Dimanche_S3',
        ),
        migrations.RenameField(
            model_name='emploi_du_temp_enseignant',
            old_name='Mardi',
            new_name='Dimanche_S4',
        ),
        migrations.RenameField(
            model_name='emploi_du_temp_enseignant',
            old_name='Mercredi',
            new_name='Jeudi_S1',
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Jeudi_S2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Jeudi_S3',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Jeudi_S4',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Lundi_S1',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Lundi_S2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Lundi_S3',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Lundi_S4',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mardi_S1',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mardi_S2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mardi_S3',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mardi_S4',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mercredi_S1',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mercredi_S2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mercredi_S3',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='Mercredi_S4',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emploi_du_temp_enseignant',
            name='semestre',
            field=models.CharField(choices=[('semestre1', 'semestre1'), ('semestre2', 'semestre2')], default='semestre1', max_length=9),
        ),
    ]
